### ISSUE TITLE
ChIP-nexus SRR data missing three samples?

### ISSUE THREAD

**Issue by endrebak** [zeitlingerlab/he_johnston_nbt_2014#1]
This is an issue about possibly missing supplementary data to the paper ["ChIP-nexus enables improved detection of in vivo transcription factor binding footprints"](http://www.nature.com/nbt/journal/v33/n4/full/nbt.3121.html).

As far as I can see, there are 18 samples listed on the GSE page for your study:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE55306

namely 

``` python
geo_samples = ["GSM1333887", "GSM1333888", "GSM1333889", "GSM1333890",
               "GSM1333891", "GSM1333892", "GSM1341814", "GSM1341815",
               "GSM1341816", "GSM1342085", "GSM1342086", "GSM1430010",
               "GSM1430011", "GSM1430012", "GSM1430013", "GSM1430014",
               "GSM1430015", "GSM1430016"]
len(geo_samples) # 18
```

However, when I try to crawl the ftp for sra files I can only find 15:

``` bash
$ mkdir sra && wget -r -nd -np -P sra -A '*.sra' ftp://ftp-trace.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByStudy/sra/SRP/SRP038/SRP038893

$ ls sra
SRR1175698.sra  SRR1175700.sra  SRR1175702.sra  SRR1185443.sra  SRR1185445.sra  SRR1185674.sra  SRR1509030.sra  SRR1509032.sra
SRR1175699.sra  SRR1175701.sra  SRR1175703.sra  SRR1185444.sra  SRR1185673.sra  SRR1509029.sra  SRR1509031.sra
```

1) How can I get the last three missing files? 
2) And how can I link GSM number to SRR number?

Thanks.

Ps. I want to use your data to compare existing ChIP-seq peak finders with a new one I have written.

**Comment by endrebak** [comment]
Forgot to ping you @jeffjjohnston.

**Comment by jeffjjohnston** [comment]
Thanks for reporting this, Endre. Indeed, the three samples with missing SRA data are:

```
GSM1430014 Twist Peconic ChIP-exo rep 1
GSM1430015 Twist Peconic ChIP-exo rep 2
GSM1430016 Twist ChIP-seq
```

I have sent a message to NCBI GEO asking about the missing SRA entries for these samples and will update this issue when I hear back from them. In the meantime, the data for the samples can also be obtained via our Amazon Machine Image for this manuscript.

You can link the GSM numbers to SRR numbers using the SRA Run Selector. Click the SRA link on the GSE page ([SRP038893](http://www.ncbi.nlm.nih.gov/sra?term=SRP038893)), then click "Send results to Run selector". That will provide a table with GSM and SRR numbers.

**Comment by jeffjjohnston** [comment]
Endre,

GEO has responded to my support request and are contacting SRA to locate the missing files. They estimate it could be a week before there's an update.

**Comment by endrebak** [comment]
Thanks for the prompt reply.

**Comment by jeffjjohnston** [comment]
Endre,

The three samples with missing SRA entries have been corrected; you should now be able to download all 18 SRA files.

**Comment by endrebak** [comment]
Super, thanks!
