### ISSUE TITLE
Is the data in SRA preprocessed?

### ISSUE THREAD

**Issue by endrebak** [zeitlingerlab/he_johnston_nbt_2014#2]
I am a bit confused about whether the data in the GEO accession viewer has been preprocessed. It seems to say it has, while the data suggests it has not been.

According to the info on the GEO accession viewer

> Custom barcode sequences were removed from the first 9bp of each read and sequencing adapters were trimmed from the 3' end using cutadapt v1.3

Has this been done or not?

According to fastqc there are a good deal of overrepresented sequences in the first positions of the reads:

```
$ w3m -dump data/fastq/SRR1175698_fastqc.html | tail -23
Sequence Count PValue Obs/Exp Max Max Obs/Exp Position
CCCTGAG  48340 0.0    43.257893   4
CCCCTGA  53530 0.0    43.064766   3
CCTGACG  30650 0.0    42.843193   5
CCCTGAC  34565 0.0    42.468464   4
GCCCTGA  40790 0.0    42.46227    3
CGCCTGA  44605 0.0    42.461914   3
CCTGAGG  35515 0.0    42.453667   5
ACCCTGA  43830 0.0    42.41201    3
CCTGAAG  58415 0.0    42.328747   5
CCCTGAA  48505 0.0    42.18313    4
CCCTGAT  40010 0.0    42.182384   4
ACCTGAG  39580 0.0    41.998375   4
CCTGAGA  58880 0.0    41.994457   5
CCTGATG  45765 0.0    41.970608   5
CCTGAGC  33355 0.0    41.884495   5
TCCCTGA  33385 0.0    41.83338    3
GCCTGAC  26620 0.0    41.655598   4
GCCTGAG  37200 0.0    41.649498   4
CTGATGT  41800 0.0    41.58158    6
CTGAGGT  25625 0.0    41.578655   6

Produced by FastQC (version 0.11.5)
```

So it seems like this has not been done.

![screen shot 2016-08-05 at 08 35 19](https://cloud.githubusercontent.com/assets/17778898/17428311/d035a11a-5ae7-11e6-9490-15ea14a888e1.png)

![screen shot 2016-08-05 at 08 35 48](https://cloud.githubusercontent.com/assets/17778898/17428322/d65430ca-5ae7-11e6-9ae5-9253faa7d342.png)

![screen shot 2016-08-05 at 08 36 09](https://cloud.githubusercontent.com/assets/17778898/17428326/dab826bc-5ae7-11e6-91bc-ea268251bf52.png)

**Comment by endrebak** [comment]
Since I see your analysis code includes `cutadapt` install instructions, I guess this was not done before the data was uploaded.

Having the data ready for alignment is something you might want to consider the next time. Aligners like Hisat2 can take an SRA number and align the data streaming it directly from the interwebs.

**Comment by endrebak** [comment]
I guess the easiest thing for me is to use an Amazon Machine Instance, run the pipelines and transfer the processed data from there. 

Great job on making an image available. I should consider doing the same with my own code.

**Comment by jeffjjohnston** [comment]
Endre,

The sequence data in SRA are the raw, unprocessed reads. It is generally GEO/SRA's policy (and that of most journals) that the original sequencing data be deposited. We also provide final processed data in the form of BigWig files as part of our GEO submission.

The preprocessed FASTQ files with the barcodes removed are available on our AMI. You would not have to generate them inside the AMI; simply look in `/data/preprocessed_fastq/` and copy what you need.
