### ISSUE TITLE
Your amazon instance is almost empty?

### ISSUE THREAD

**Issue by endrebak** [zeitlingerlab/he_johnston_nbt_2014#3]
@jeffjjohnston 

Thanks again for making the data available, both on GEO and as a container.

I have a question about your amazon instance.

This is what I get after logging in to your instance:

```
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-36-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Mon Aug  8 07:16:13 UTC 2016

  System load:  0.0                 Processes:           416
  Usage of /:   72.8% of 147.51GB   Users logged in:     0
  Memory usage: 0%                  IP address for eth0: 172.31.56.83
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

9 packages can be updated.
9 updates are security updates.

New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** /dev/xvda1 should be checked for errors ***

$ ls -latrh
total 56K
-rw-r--r-- 1 ubuntu ubuntu  675 Apr  9  2014 .profile
-rw-r--r-- 1 ubuntu ubuntu  220 Apr  9  2014 .bash_logout
drwxr-xr-x 3 root   root   4.0K Oct 22  2014 ..
drwx------ 2 ubuntu ubuntu 4.0K Oct 22  2014 .ssh
drwx------ 2 ubuntu ubuntu 4.0K Oct 22  2014 .cache
-rwxrwxr-x 1 ubuntu ubuntu  106 Oct 22  2014 add_swap.sh
drwx------ 3 ubuntu ubuntu 4.0K Oct 22  2014 .config
-rw-rw-r-- 1 ubuntu ubuntu  414 Oct 22  2014 .Rprofile
drwxr-xr-x 4 root   root   4.0K Oct 22  2014 .cabal
drwx------ 2 ubuntu ubuntu 4.0K Oct 23  2014 .ncbi
drwxrwxr-x 3 ubuntu ubuntu 4.0K Oct 23  2014 ncbi
-rw-r--r-- 1 ubuntu ubuntu 3.6K Oct 24  2014 .bashrc
-rw------- 1 root   root    705 Oct 27  2014 .viminfo
drwxr-xr-x 8 ubuntu ubuntu 4.0K Oct 27  2014 .
```

If it were not for the `.Rprofile` containing a `bioconductor` reference and the 2014 dates, I would have guessed it was an empty instance, not yours.

1) Was the instance meant to contain so little data on startup? I expected the analysis code, data files and intermediate results to be there. If this is the way the image is supposed to be, you might want to add a note about it in your README. If not, I'll try to help you debug why this happens by running commands on my end.

This is what I did to connect to your instance (perhaps it would be helpful to add these instructions to the README?):

```
$ cp ~/Downloads/HeJohnstonInstance.pem ~/.ssh
$ sudo chmod 600 ~/.ssh/HeJohnstonInstance.pem
$ ssh-add ~/.ssh/HeJohnstonInstance.pem
$ ssh ubuntu@54.175.76.243
```

Also please note the warning on login:

**/dev/xvda1 should be checked for errors**

**Comment by endrebak** [comment]
This is my info:

```
Instance ID
i-0f916d25dce35dcc2
Public DNS
ec2-54-175-76-243.compute-1.amazonaws.com
Instance state
running
Public IP
54.175.76.243
Instance type
c3.4xlarge
Elastic IPs
Private DNS
ip-172-31-56-83.ec2.internal
Availability zone
us-east-1a
Private IPs
172.31.56.83
Security groups
launch-wizard-1. view rules
Secondary private IPs
Scheduled events
No scheduled events
VPC ID
vpc-debed0b9
AMI ID
ChIP-nexus manuscript analysis code (Nature Biotechnology 2014) (ami-f041da98)
Subnet ID
subnet-43b1b169
Platform
-
Network interfaces
eth0
IAM role
-
Source/dest. check
True
Key pair name
HeJohnstonInstance
Owner
630366258038
EBS-optimized
False
Launch time
August 8, 2016 at 9:08:32 AM UTC+2 (less than one hour)
Root device type
ebs
Termination protection
False
Root device
/dev/sda1
Lifecycle
normal
Block devices
/dev/sda1
Monitoring
basic
Alarm status
None
Kernel ID
-
RAM disk ID
-
Placement group
-
Virtualization
hvm
Reservation
r-0c3731c0295c18277
AMI launch index
0
Tenancy
default
Host ID
-
Affinity
-
State transition reason
```

**Comment by endrebak** [comment]
Btw, do you get e-mail notifications when I ping you here, or should I send an e-mail myself? Thanks.

**Comment by jeffjjohnston** [comment]
Endre,

Everything is in the `/data/` directory on the instance. See our [AMI setup instructions](https://github.com/zeitlingerlab/he_johnston_nbt_2014/blob/master/ami/ami_setup_notes.md) for details on how everything was generated. I believe you might be looking for the processed ChIP-nexus FASTQ files that are ready for alignment. These are in `/data/preprocessed_fastq/`.

Regarding the warning about /dev/xvda1, I believe that is an automatic message triggered by how much time has past between me generating the image and your launching of an instance. The instance is not configured to perform a filesystem check on startup as that could take a considerable amount of time due to the volume's size.

Thanks for trying out the instance and for the feedback! Please let me know if you have any additional questions.

**Comment by endrebak** [comment]
Thanks, all the files were in the root data directory 👍
