### ISSUE TITLE
Can I use some of your data in an image of my own?

### ISSUE THREAD

**Issue by endrebak** [zeitlingerlab/he_johnston_nbt_2014#4]
@jeffjjohnston Your image was so helpful that I want to try to create a docker image with data/code for the application note I am writing. Can I include some of your data? I am especially interested in the bed files and the peaks you found.

Is this ok for you and in general? I'll cite your paper obviously.

**Comment by jeffjjohnston** [comment]
That's certainly okay with us! You can include any of the data in the instance. I also really like the idea of using Docker instead of a virtual machine if you don't need a huge amount of data stored in your image.
