### ISSUE TITLE
Was macs run on 1 or 2 files at a time?

### ISSUE THREAD

**Issue by endrebak** [zeitlingerlab/he_johnston_nbt_2014#5]
@jeffjjohnston I have one more question for you. Please answer it at your leisure.

In the `/data/macs` folder I can find 14 `.narrowPeak` files, but 20 `.bgz` files.

Normally, I'd assume that the samples for each type (exo or nexus) were merged or input to macs in the same run, but that is unlikely to be it since the `.narrowPeak` files have sample numbers:

```
dmel_embryo_dl_chipnexus_01_peaks.narrowPeak   dmel_embryo_twi_chipseq_01_peaks.narrowPeak  dmel_s2_myc_chipnexus_02_peaks.narrowPeak
dmel_embryo_dl_chipnexus_02_peaks.narrowPeak   dmel_s2_max_chipnexus_01_peaks.narrowPeak    hsap_k562_tbp_chipnexus_01_peaks.narrowPeak
dmel_embryo_dl_chipseq_01_peaks.narrowPeak     dmel_s2_max_chipnexus_02_peaks.narrowPeak    hsap_k562_tbp_chipnexus_02_peaks.narrowPeak
dmel_embryo_twi_chipnexus_01_peaks.narrowPeak  dmel_s2_max_chipseq_01_peaks.narrowPeak      hsap_k562_tbp_chipseq_01_peaks.narrowPeak
dmel_embryo_twi_chipnexus_02_peaks.narrowPeak  dmel_s2_myc_chipnexus_01_peaks.narrowPeak
```

Here are the input files:

```
dmel_embryo_dl_chipexo_01.bed.bgz    dmel_embryo_twi_chipexo_01.bed.bgz    dmel_s2_max_chipnexus_01.bed.bgz  hsap_k562_tbp_chipexo_01.bed.bgz
dmel_embryo_dl_chipexo_02.bed.bgz    dmel_embryo_twi_chipexo_02.bed.bgz    dmel_s2_max_chipnexus_02.bed.bgz  hsap_k562_tbp_chipexo_02.bed.bgz
dmel_embryo_dl_chipnexus_01.bed.bgz  dmel_embryo_twi_chipnexus_01.bed.bgz  dmel_s2_max_chipseq_01.bed.bgz    hsap_k562_tbp_chipnexus_01.bed.bgz
dmel_embryo_dl_chipnexus_02.bed.bgz  dmel_embryo_twi_chipnexus_02.bed.bgz  dmel_s2_myc_chipnexus_01.bed.bgz  hsap_k562_tbp_chipnexus_02.bed.bgz
dmel_embryo_dl_chipseq_01.bed.bgz    dmel_embryo_twi_chipseq_01.bed.bgz    dmel_s2_myc_chipnexus_02.bed.bgz  hsap_k562_tbp_chipseq_01.bed.bgz
```

Which bgz files correspond to which narrowPeak? Or is the relationship 1 to 1, but there were some bgz files that you did not call MACS2 on?

Thanks.

**Comment by jeffjjohnston** [comment]
Hi Endre,

MACS2 was run on 1 BED file at a time and the output is the same as the BED file (without extension) but with `_peaks.narrowPeak` appended. We ran MACS2 on all the ChIP-nexus and ChIP-seq samples, but not the ChIP-exo samples - those 6 account for the missing `.narrowPeak` files.
